# Generated by Django 2.1 on 2018-09-04 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=20)),
                ('album_image', models.FileField(upload_to='')),
                ('created_by', models.CharField(max_length=50)),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('Image_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Album')),
            ],
        ),
    ]
